//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorLivro
    {
        public int IdAutorLivro { get; set; }
        public int IdLivro { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Livro Livro { get; set; }
        public virtual Autor Autor { get; set; }
    }
}
