//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Venda = new HashSet<Venda>();
        }
    
        public int IdFuncionario { get; set; }

        [Required(ErrorMessage = "Insira o nome do funcionario!", AllowEmptyStrings = false)]
        public string NomeFuncionario { get; set; }

        [Required(ErrorMessage = "Informe o nome do usuário!", AllowEmptyStrings = false)]
        public string Login { get; set; }

        [Required(ErrorMessage = "Insira a senha do usuário!", AllowEmptyStrings = false)]
        public string Senha { get; set; }
        public bool Administrador { get; set; }
    
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
