//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Model
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class ItemVenda
    {
        public int Id { get; set; }

        [Required(ErrorMessage="Houve um problema com a inserção da venda!")]
        public int IdVenda { get; set; }

        [Required(ErrorMessage="Houve um problema com a inserção da venda!")]
        public int IdLivro { get; set; }

        [Required(ErrorMessage="Houve um problema com a inserção da venda!")]
        public int Quantidade { get; set; }
    
        public virtual Venda Venda { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
