//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public Venda()
        {
            this.Item_Venda = new HashSet<Item_Venda>();
        }
    
        public int IdVenda { get; set; }
        public System.DateTime DataVenda { get; set; }
        public decimal PrecoTotal { get; set; }
        public int TotalLivros { get; set; }
        public int IdFuncionario { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual ICollection<Item_Venda> Item_Venda { get; set; }
    }
}
