//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Venda
    {
        public Venda()
        {
            this.Item_Venda = new HashSet<ItemVenda>();
        }
    
        public int IdVenda { get; set; }

        [Required(ErrorMessage = "Insira a data da venda!")]
        public System.DateTime DataVenda { get; set; }

        [Required(ErrorMessage="Selecione livros para realizar a venda!")]
        public decimal PrecoTotal { get; set; }

        [Required(ErrorMessage = "Selecione livros para realizar a venda!")]
        public int TotalLivros { get; set; }

        [Required(ErrorMessage = "Selecione o funcionário deste venda!")]
        public int IdFuncionario { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual ICollection<ItemVenda> Item_Venda { get; set; }
    }
}
